Algoritmo "soma"
// Problema "soma"
// Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes números.

// Autor(a)    : Amarick
// Data atual  : 29/09/2023
Var
valor_1, valor_2, soma : inteiro


Inicio

escreval("Digite dois valores")
leia(valor_1)
leia(valor_2)

soma <- valor_1 + valor_2
escreva("A soma dos valores digitados é = ",soma)


Fimalgoritmo