Algoritmo "crescente"

// Autor(a)    : Amarick
// Data atual  : 19/10/2023
Var
numero1, numero2 : inteiro


Inicio
escreval("Digite dois numero: ")
leia(numero1)
leia(numero2)

enquanto numero1 <> numero2 faca
   se numero1 < numero2 entao
      escreval("CRESCENTE")
   senao
      escreval("DECRESCENTE")
   fimse
   

escreval("Digite outros dois numeros: ")
leia(numero1)
leia(numero2)

fimenquanto


Fimalgoritmo