Algoritmo "soma_2"
// Problema "soma"
// Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes números.

// Autor(a)    : Amarick
// Data atual  : 29/09/2023
Var
numero_1, numero_2, soma: inteiro


Inicio

escreva("Digite o valor de X: ")
leia(numero_1)

escreva("Digite o valor de Y: ")
leia(numero_2)

soma <- numero_1 + numero_2

escreva("Soma = ",soma)


Fimalgoritmo