funcao media(a: real; b: real) : real
var
   soma : real
inicio
      soma <- a + b
      retorne soma / 2
fimfuncao

Algoritmo "aula_funcoes"

Var

altura1, altura2, resultado : real

Inicio

escreval("Entre com duas alturas por favor: ")
leia(altura1)
leia(altura2)

resultado <-  media (altura1, altura2)

escreval("Resultado = ", resultado:4:2)









Fimalgoritmo